# Cache setup was modified from https://github.com/coollog/jib-google-cloud-build/blob/master/cloudbuild-jib-maven%2Bcache.yaml
steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    dir: /root
    entrypoint: bash
    args:
      - '-c'
      - (gsutil cp gs://${_GCS_CACHE_BUCKET}/${BRANCH_NAME}/m2.tar.gz /tmp/m2.tar.gz && tar -xzf /tmp/m2.tar.gz) || echo 'Maven cache not found'
    volumes:
      - name: maven-cache
        path: /root/.m2
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    dir: /root
    entrypoint: bash
    args:
      - '-c'
      - (gsutil cp gs://${_GCS_CACHE_BUCKET}/${BRANCH_NAME}/jib.tar.gz /tmp/jib.tar.gz && tar -xzf /tmp/jib.tar.gz) || echo 'Jib cache not found'
    volumes:
      - name: jib-cache
        path: /root/.cache/google-cloud-tools-java/jib
  - name: maven:3.9.1-eclipse-temurin-17
    entrypoint: mvn
    args: ['dependency:go-offline', '-B']
    volumes:
      - name: maven-cache
        path: /root/.m2
  - name: maven:3.9.1-eclipse-temurin-17
    entrypoint: mvn
    args:
      [
        'package',
        'jib:build',
        '-pl',
        '${_SERVICE_NAME}',
        '-am',
        '-DskipTests=true',
        '-Dimage=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}',
        '-B',
      ]
    volumes:
      - name: maven-cache
        path: /root/.m2
      - name: jib-cache
        path: /root/.cache/google-cloud-tools-java/jib
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      [
        'deploy',
        'releases',
        'create',
        'release-$$DATE-$$TIME',
        '--skaffold-file',
        './${_SERVICE_NAME}/deploy/skaffold.yaml',
        '--delivery-pipeline',
        '${_SERVICE_NAME}-delivery-pipeline',
        '--region',
        '${_REGION}',
        '--images',
        'app-image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}',
      ]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    dir: /root
    entrypoint: bash
    args:
      - '-c'
      - (tar -czf /tmp/m2.tar.gz .m2 && gsutil cp /tmp/m2.tar.gz gs://${_GCS_CACHE_BUCKET}/${BRANCH_NAME}/m2.tar.gz) || echo 'Failed to save Maven cache'
    volumes:
      - name: maven-cache
        path: /root/.m2
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    dir: /root
    entrypoint: bash
    args:
      - '-c'
      - (tar -czf /tmp/jib.tar.gz .cache/google-cloud-tools-java/jib && gsutil cp /tmp/jib.tar.gz gs://${_GCS_CACHE_BUCKET}/${BRANCH_NAME}/jib.tar.gz) || echo 'Failed to save Jib cache'
    volumes:
      - name: jib-cache
        path: /root/.cache/google-cloud-tools-java/jib

options:
  dynamic_substitutions: true

substitutions:
  _SERVICE_NAME: api-jobs
