name: Maven

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install dependencies
        run: mvn dependency:go-offline -B
      - name: Build with Maven
        run: mvn compile -B
      - name: Package with Maven
        run: mvn package -B -DskipTests=true
      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: api-artifacts
          path: '**/target/*.jar'
  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install dependencies
        run: mvn dependency:go-offline -B
      - name: Run tests
        run: mvn test -B -Dspring.profiles.active=h2
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
